### ISSUE TITLE
operational states validation

### ISSUE THREAD

**Issue by ksator** [Juniper/salt#45]
### Description of enhancement

Ability to use SaltStack to validate operational states (compare an operational state against a predefined value).  
Example: bgp sessions state has to be equal to Established. so add the ability to test if actual operational state is equal to the desired operational state. Other comparaison operator than equal are importants as well.     

Like Ansible does with junos-command module using the wait_for optional argument. 
Example with Ansible: https://github.com/ksator/junos-automation-with-ansible/blob/master/junos_command/pb_check_op_states.yml#L47-L155

**Comment by vnitinv** [comment]
@ksator I think this can be achieved using jinja template based state file, where we can loop for a given number and call API to check the state during each run and also might be able to sleep for a given time.
I will try to get an example for this.
Let me know if this is what you are looking for.

**Comment by ksator** [comment]
@vnitinv Many thanks. It sounds like a plan. Could you please share an example?

**Comment by rsmekala** [comment]
@ksator, Are you looking for something like this ??

```
wait_for_connection_to_be_up:
  loop.until:
    - name: junos.rpc
    - condition: m_ret['rpc_reply']['interface-information']['physical-interface']['admin-status'] == 'up'
    - period: 5
    - timeout: 20
    - m_args:
      - get-interface-information
    - m_kwargs:
        interface_name: lo0
```

Salt loops : https://docs.saltstack.com/en/latest/ref/states/all/salt.states.loop.html

The above-suggested way will work on salt > 2017.7.0
